### ISSUE TITLE
Labels too big, small them up

### ISSUE THREAD

**Issue by brunocordioli** [StiickCo/stiickstock-front#108]

**Comment by NotGecko** [comment]
Feito.
Antes:
![image](https://user-images.githubusercontent.com/45054511/71496827-11c8bc80-2834-11ea-987d-e7773cead39d.png)

Depois:
![image](https://user-images.githubusercontent.com/45054511/71496834-1ab98e00-2834-11ea-99df-709c21622d16.png)
