### ISSUE TITLE
Personalize Welcome Page

### ISSUE THREAD

**Issue by brunocordioli** [StiickCo/stiickstock-front#22]

**Comment by brunocordioli** [comment]
A tela tera graficos aleatorios por enquanto que terão valores de acordo com os produtos do sistema.
https://vuetifyjs.com/en/components/sparklines/#examples
A tela tera 3 graficos, um de produtos adicionados, um de emails inscritos, um de produtos vendidos. respectivamente.

**Comment by NotGecko** [comment]
[Sparklines]( https://vuetifyjs.com/en/components/sparklines/) do vuetify não tem como colocar labels de valores no eixo y
![image](https://user-images.githubusercontent.com/45054511/71056529-5c617f00-2138-11ea-9603-3041d48b6d80.png)

Se a gente quiser colocar os valores na lateral dá de usar o [vue-chartjs](https://vue-chartjs.org/) pra fazer os gráficos
![image](https://user-images.githubusercontent.com/45054511/71056596-9d599380-2138-11ea-9335-e3504aaf79c7.png)

[Mais exemplos dos gráficos ](http://demo.vue-chartjs.org/)

**Comment by NotGecko** [comment]
Primeira implementação de base feita, questão de visual e deixar o código mais limpo será feito em breve
