### ISSUE TITLE
Login page has errors

### ISSUE THREAD

**Issue by brunocordioli** [StiickCo/stiickstock-front#4]
Na hora que tu clica para escrever um email e depois clica fora sem escrever nada aparece o negocinho vermelho que ta invalido o email, sendo que nao ta.

**Comment by Eric-Liz** [comment]
O erro ao clicar fora sem escrever nenhum email foi resolvido, porém, agora não aparece erro nem mesmo ao tentar entrar com login errado (ou sem email / senha).

**Comment by brunocordioli** [comment]
dai em vez de conserta pioro
