### ISSUE TITLE
Make validation to add Product

### ISSUE THREAD

**Issue by brunocordioli** [StiickCo/stiickstock-front#75]

**Comment by brunocordioli** [comment]
Inputs dentro do pop up de adicionar produto devem ser validados: não podem ser inseridas caracteres especias. Tamanho do nome, etc

**Comment by brunocordioli** [comment]
não esquecer de retirar o type:number dos inputs: preço unitario e quantidades de produtos no estoque. A validação que se encarregará de verificar se são ou não numeros.

**Comment by NotGecko** [comment]
Validação talvez possa ser feita utilizando [validation](https://vuetifyjs.com/en/components/text-fields#validation) (text field)/[rules](https://vuetifyjs.com/en/components/text-fields#validation)  (input)
